services:
  mysql:
    image: mysql:8.0.36
    environment:
      - MYSQL_ROOT_PASSWORD=aparavi
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: mysqld --innodb_print_all_deadlocks=1 --innodb_buffer_pool_instances=16 --innodb_buffer_pool_size=4GB --disable-log-bin
    ports:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  platform:
    image: aparavi/aparavi:2.20.2-25611
    ports:
      - 9452
    environment:
      - APARAVI_PLATFORM=ea.aparavi.com
      - APARAVI_DBHOST=mysql
      - APARAVI_DBPORT=3306
      - APARAVI_DBUSER=root
      - APARAVI_DBPASS=aparavi
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=12288
    volumes:
      - ./platform-data:/var/lib/aparavi-data-ia
      - ./platform-config:/etc/opt/aparavi-data-ia
      - type: bind
        source: ./python/site-packages
        target: /opt/aparavi-data-ia/app/engine/linux/lib/python3.10/site-packages
    healthcheck:
      test: ["CMD", "curl", "--fail","--head", "http://localhost:9452/server/api"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  appagent:
    image: aparavi/aparavi:2.20.2-25611
    environment:
      - APPTYPE=appagt
      - APARAVI_PLATFORM=platform
      - APARAVI_PARENT=CLIENTS
      - APARAVI_DBHOST=mysql
      - APARAVI_DBPORT=3306
      - APARAVI_DBUSER=root
      - APARAVI_DBPASS=aparavi
      - APARAVI_ANALYTICS=true
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=12288
    volumes:
      - ./appagent-data:/var/lib/aparavi-data-ia
      - ./appagent-config:/etc/opt/aparavi-data-ia
      - ./source-data:/source
      - type: bind
        source: ./python/site-packages
        target: /opt/aparavi-data-ia/app/engine/linux/lib/python3.10/site-packages
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9752/server/api"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      platform:
        condition: service_healthy
      mysql:
        condition: service_healthy
